import { useState } from 'react';
import { supabase, money } from '../../lib';
import type { Inquiry } from '../../types';
import AdminHeader from './AdminHeader';
export default function AdminInquiries({inq,refresh,onToast}:{inq:Inquiry[];refresh:()=>void;onToast:(x:string)=>void}){
 const [open,setOpen]=useState<string|null>(null);
 const setStatus=async(i:Inquiry,status:Inquiry['status'])=>{if(!supabase)return;const {error}=await supabase.rpc('admin_set_request_status',{p_request_id:i.id,p_status:status});if(error)onToast(error.message);else refresh()};
 const setValue=async(i:Inquiry,value:number)=>{if(!supabase)return;const {error}=await supabase.rpc('admin_set_order_value',{p_request_id:i.id,p_value:value,p_reason:'Admin-Korrektur'});if(error)onToast(error.message);else refresh()};
 return <><AdminHeader title="Kundenanfragen"/><div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Anfrage</th><th>Betrieb</th><th>Kunde</th><th>Problem</th><th>Status</th><th>Auftragswert</th><th>Provision</th><th></th></tr></thead><tbody>{inq.map(i=><tr key={i.id}><td><b>{i.request_code}</b><div className="small muted">{new Date(i.created_at).toLocaleString('de-DE')}</div></td><td>{i.business_name||'Nicht zugeordnet'}</td><td>{i.customer_name}<div className="small">{i.customer_postal_code} {i.customer_city}</div></td><td>{i.problem}<div className="small muted">{i.brand||''} {i.model||''}</div></td><td><select value={i.status} onChange={e=>setStatus(i,e.target.value as any)}>{['new','assigned','contacted','in_progress','completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td><td><input className="table-input" type="number" min="0" step="0.01" defaultValue={i.order_value} onBlur={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n!==i.order_value)void setValue(i,n)}}/>{i.invoice_status&&<div className="small muted">{i.invoice_status}</div>}</td><td>{money(i.commission_amount)}</td><td><button className="small secondary" onClick={()=>setOpen(open===i.id?null:i.id)}>{open===i.id?'Schließen':'Details'}</button></td></tr>)}</tbody></table>{open&&(()=>{const i=inq.find(x=>x.id===open);if(!i)return null;return <div className="card" style={{marginTop:16}}><h3>{i.request_code}</h3><p>{i.customer_name}<br/>{i.customer_phone}<br/>{i.customer_email}</p><p><b>Adresse:</b><br/>{i.customer_postal_code} {i.customer_city}</p><p><b>Problem:</b><br/>{i.problem_description}</p><p><b>Termin:</b> {i.preferred_date||'—'} {i.preferred_time||''}</p></div>})()}{!inq.length&&<div className="empty">Noch keine Kundenanfragen vorhanden.</div>}</div></div></>;
}
