import { useEffect, useState } from 'react';
import { Activity, ArrowRight, Building2, FileText, Home as HomeIcon, Users, Wallet } from 'lucide-react';
import { cls, supabase } from '../../lib';
import type { AppRow, Business, Inquiry, Invoice } from '../../types';
import AdminHome from './AdminHome';
import AdminBusinesses from './AdminBusinesses';
import AdminApps from './AdminApps';
import AdminInquiries from './AdminInquiries';
import AdminInvoices from './AdminInvoices';
import AdminAudit from './AdminAudit';
function AdminDashboard({onToast}:{onToast:(x:string)=>void}){const [tab,setTab]=useState('dashboard');const [biz,setBiz]=useState<Business[]>([]);const [apps,setApps]=useState<AppRow[]>([]);const [inq,setInq]=useState<Inquiry[]>([]);const [inv,setInv]=useState<Invoice[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{refresh()},[]);const refresh=async()=>{if(!supabase)return;setLoading(true);const [b,a,i,v]=await Promise.all([supabase.from('businesses').select('*').order('created_at',{ascending:false}),supabase.from('partner_applications').select('*').order('created_at',{ascending:false}),supabase.from('inquiries').select('*').order('created_at',{ascending:false}),supabase.from('invoices').select('*').order('created_at',{ascending:false})]);setBiz((b.data||[]) as Business[]);setApps((a.data||[]) as AppRow[]);setInq((i.data||[]) as Inquiry[]);setInv((v.data||[]) as Invoice[]);setLoading(false)};if(loading)return <main><section className="page-top"><div className="shell"><div className="empty loading"><Activity className="spin"/> Admin-Daten werden geladen …</div></div></section></main>;const completed=inq.filter(x=>x.status==='completed');const volume=completed.reduce((s,x)=>s+Number(x.order_value),0);const commission=completed.reduce((s,x)=>s+Number(x.commission_amount),0);return <main className="admin-page"><div className="admin-shell"><aside className="admin-side"><div className="admin-brand">WASCH<span>MATIK</span><small>Administration</small></div>{[['dashboard',HomeIcon,'Dashboard'],['businesses',Building2,'Reparaturbetriebe'],['applications',Users,'Partneranfragen'],['inquiries',FileText,'Kundenanfragen'],['invoices',Wallet,'Abrechnungen'],['audit',Activity,'Audit-Log']].map(([k,I,t])=>{const Icon=I as any;return <button className={cls('side-btn',tab===k&&'active')} onClick={()=>setTab(k as string)} key={k as string}><Icon size={18}/>{t as string}</button>})}<button className="side-btn" onClick={()=>window.location.href='https://waschmatik.de/'}><ArrowRight size={18}/>Öffentliche Website</button><button className="side-btn danger" onClick={()=>supabase?.auth.signOut()}>Abmelden</button></aside><section className="admin-content">{tab==='dashboard'&&<AdminHome biz={biz} apps={apps} inq={inq} inv={inv} volume={volume} commission={commission}/>} {tab==='businesses'&&<AdminBusinesses biz={biz} refresh={refresh}/>} {tab==='applications'&&<AdminApps apps={apps} refresh={refresh}/>} {tab==='inquiries'&&<AdminInquiries inq={inq} refresh={refresh} onToast={onToast}/>} {tab==='invoices'&&<AdminInvoices inv={inv} refresh={refresh}/>} {tab==='audit'&&<AdminAudit/>}</section></div></main>}

export default AdminDashboard;
