import React, { FormEvent, useEffect, useState } from 'react';
import { Mail } from 'lucide-react';
import { supabase } from '../../lib';
function AuthCard({mode,onApproved,onSession}:{mode:'admin'|'partner';onApproved?:()=>void;onSession?:(s:any)=>void}){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [requestId,setRequestId]=useState<string|null>(null); const [expiresAt,setExpiresAt]=useState<string|null>(null); const [error,setError]=useState('');
 useEffect(()=>{const client=supabase;if(!requestId||!client)return;const timer=setInterval(async()=>{const {data:r}=await client.from('admin_login_requests').select('status,expires_at').eq('id',requestId).maybeSingle();if(!r)return;if(r.status==='approved'){clearInterval(timer);onApproved?.();setBusy(false);return}else if(new Date(r.expires_at).getTime()<Date.now()){clearInterval(timer);setError('Die Freigabe ist abgelaufen. Bitte erneut anmelden.');setRequestId(null)}},2500);return()=>clearInterval(timer)},[requestId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(!supabase)return;const normalized=email.trim().toLowerCase();const adminEmail=(import.meta.env.VITE_ADMIN_LOGIN_EMAIL||'waschmatik@gmail.com').trim().toLowerCase();if(mode==='admin'&&normalized!==adminEmail){setError('Für den Adminbereich ist ausschließlich die WASCHMATIK-Administrationsadresse zugelassen.');return}setBusy(true);const {data:loginData,error:loginError}=await supabase.auth.signInWithPassword({email:normalized,password});if(loginError){setBusy(false);setError('E-Mail oder Passwort ist nicht korrekt.');return}
   if(mode==='admin'){onSession?.(loginData.session);const {data, error:approvalError}=await supabase.functions.invoke('request-admin-approval');if(approvalError||!data?.request_id){await supabase.auth.signOut();setBusy(false);setError('Die zweite Sicherheitsstufe konnte nicht gestartet werden.');return}setRequestId(data.request_id);setExpiresAt(data.expires_at||null)}
   setBusy(false);
 };
 const logout=async()=>{await supabase?.auth.signOut();setRequestId(null);setExpiresAt(null)};
 return <main><section className="page-top"><div className="shell"><div className="auth-wrap"><div className="card auth-card"><div className="eyebrow">GESCHÜTZTER BEREICH</div><h1>{mode==='admin'?'Admin-Login':'Partner-Login'}</h1>
 {requestId?<><p><b>Schritt 2 von 2:</b> Eine neue Freigabe-Mail wurde an die hinterlegte WASCHMATIK-Adminadresse gesendet.</p><div className="security-box"><Mail size={22}/><div><b>Freigabe ausstehend</b><span>Öffne die E-Mail und bestätige den Login. Danach wird dieser Zugang automatisch freigeschaltet.</span>{expiresAt&&<small>Gültig bis {new Date(expiresAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr</small>}</div></div><button className="secondary full" onClick={logout}>Abbrechen und abmelden</button></>:<><p>{mode==='admin'?'E-Mail und Passwort werden geprüft. Danach wird zusätzlich eine Freigabe per E-Mail an WASCHMATIK verlangt.':'Sicherer Login über Supabase Auth.'}</p><form onSubmit={submit}><label>E-Mail</label><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/><label>Passwort</label><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="form-error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Wird geprüft …':'Weiter'}</button></form></>}</div></div></div></section></main>
}

export default AuthCard;
