import { FormEvent, useState } from 'react';
import { X } from 'lucide-react';
import { supabase } from '../../lib';
import type { Business } from '../../types';
import Field from '../shared/Field';
function BusinessForm({initial,close,refresh}:{initial:Business|null;close:()=>void;refresh:()=>void}){
 const [saving,setSaving]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);setSaving(true);const payload={business_name:String(f.get('business_name')||''),contact_name:String(f.get('contact_name')||''),email:String(f.get('email')||'').trim().toLowerCase(),phone:String(f.get('phone')||''),street:String(f.get('street')||''),house_number:String(f.get('house_number')||''),postal_code:String(f.get('postal_code')||''),city:String(f.get('city')||''),website:String(f.get('website')||''),description:String(f.get('description')||''),status:String(f.get('status')||'pending'),commission_percent:Number(f.get('commission_percent')||5)};let error;if(initial){({error}=await supabase.from('partners').update(payload).eq('id',initial.id));}else {({error}=await supabase.from('partners').insert(payload));}setSaving(false);if(error)alert(error.message);else{close();refresh()}};
 return <div className="modal-backdrop"><div className="modal wide"><button className="close" onClick={close}><X/></button><div className="eyebrow">ADMIN</div><h2>{initial?'Partner bearbeiten':'Neuen Partner hinzufügen'}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Betriebsname" name="business_name" required defaultValue={initial?.name||''}/><Field label="Ansprechpartner" name="contact_name" defaultValue={initial?.contact_name||''}/><Field label="E-Mail" name="email" type="email" defaultValue={initial?.email||''}/><Field label="Telefon" name="phone" defaultValue={initial?.phone||''}/><Field label="Straße" name="street" defaultValue={initial?.street||''}/><Field label="Hausnummer" name="house_number" defaultValue={initial?.house_number||''}/><Field label="PLZ" name="postal_code" defaultValue={initial?.postal_code||''}/><Field label="Ort" name="city" required defaultValue={initial?.city||''}/><Field label="Website" name="website" type="url" defaultValue={initial?.website||''}/><Field label="Provision %" name="commission_percent" type="number" defaultValue={initial?.commission_percent||5}/><div><label>Status</label><select name="status" defaultValue={initial?.status||'pending'}><option value="pending">pending</option><option value="active">active</option><option value="paused">paused</option><option value="inactive">inactive</option></select></div><div className="full"><label>Beschreibung</label><textarea name="description" defaultValue={initial?.description||''}/></div></div><button className="primary full" disabled={saving}>{saving?'Speichern …':'Partner speichern'}</button></form></div></div>
}
export default BusinessForm;
