import { FormEvent, useState } from 'react';
import { ShieldCheck, Mail } from 'lucide-react';
import { supabase } from '../../lib';
function PartnerApply({onToast}:{onToast?:(x:string)=>void}){
 const [sending,setSending]=useState(false);const [done,setDone]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase){onToast?.('Backend nicht verbunden.');return}const f=new FormData(e.currentTarget);const areas=String(f.get('service_postal_codes')||'').split(/[,\s]+/).map(x=>x.trim()).filter(Boolean);setSending(true);const {data,error}=await supabase.rpc('submit_partner_application',{p_business_name:String(f.get('business_name')||''),p_contact_name:String(f.get('contact_name')||''),p_email:String(f.get('email')||''),p_phone:String(f.get('phone')||''),p_street:String(f.get('street')||''),p_house_number:String(f.get('house_number')||''),p_postal_code:String(f.get('postal_code')||''),p_city:String(f.get('city')||''),p_website:String(f.get('website')||''),p_description:String(f.get('description')||''),p_service_postal_codes:areas});setSending(false);if(error){onToast?.(error.message);return}setDone(true);void data};
 if(done)return <main><section className="page-top"><div className="shell"><div className="card auth-card"><div className="eyebrow">ANFRAGE ERHALTEN</div><h1>Danke für deine Partneranfrage!</h1><p>Wir prüfen deine Betriebsdaten manuell. Bei Rückfragen melden wir uns über die angegebene E-Mail-Adresse.</p><a className="primary btn-link" href="mailto:waschmatik@gmail.com"><Mail size={18}/> Kontakt zu WASCHMATIK</a></div></div></section></main>;
 return <main><section className="page-top"><div className="shell"><div className="eyebrow">FÜR REPARATURBETRIEBE</div><h1>Werde WASCHMATIK-Partner</h1><p>Reiche deine Betriebsdaten ein. Neue Partner werden vor der öffentlichen Freischaltung manuell geprüft.</p></div></section><section><div className="shell two-col"><div className="card partner-apply-card"><div className="security-box"><ShieldCheck size={22}/><div><b>Manuelle Prüfung</b><span>Deine Angaben landen direkt in der WASCHMATIK-Datenbank und werden erst nach Prüfung öffentlich aktiv.</span></div></div><h2>So läuft es ab</h2><ol className="timeline"><li>Betriebsdaten einreichen</li><li>Servicegebiet angeben</li><li>Prüfung durch WASCHMATIK</li><li>Freischaltung als aktiver Partner</li></ol><p className="small muted">Keine Passwörter oder sensiblen Daten eintragen.</p></div><div className="card partner-apply-card"><div className="eyebrow">PARTNERANFRAGE</div><h2>Betrieb anmelden</h2><form onSubmit={submit}><div className="form-grid"><div><label>Betriebsname *</label><input name="business_name" required/></div><div><label>Ansprechpartner *</label><input name="contact_name" required/></div><div><label>E-Mail *</label><input name="email" type="email" required/></div><div><label>Telefon *</label><input name="phone" required/></div><div><label>Straße</label><input name="street"/></div><div><label>Hausnummer</label><input name="house_number"/></div><div><label>PLZ *</label><input name="postal_code" inputMode="numeric" maxLength={5} required/></div><div><label>Ort *</label><input name="city" required/></div><div className="full"><label>Website</label><input name="website" type="url" placeholder="https://"/></div><div className="full"><label>Service-PLZ *</label><input name="service_postal_codes" placeholder="z. B. 41542, 41460, 50667" required/></div><div className="full"><label>Unternehmensbeschreibung</label><textarea name="description" maxLength={2000}/></div></div><button className="primary full" disabled={sending}>{sending?'Wird übermittelt …':'Partneranfrage absenden'}</button></form></div></div></section></main>;
}
export default PartnerApply;
