import { useEffect, useState } from 'react';
import { Building2, FileText, Home as HomeIcon, Wallet } from 'lucide-react';
import { money, supabase } from '../../lib';
import AdminHeader from '../admin/AdminHeader';
export default function PartnerDashboard({onToast}:{onToast:(x:string)=>void}){
 const [partner,setPartner]=useState<any>(null); const [requests,setRequests]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]); const load=async()=>{if(!supabase)return;const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)return;const {data:role}=await supabase.from('user_roles').select('business_id').eq('user_id',uid).eq('role','partner').maybeSingle();if(!role?.business_id)return;const [{data:p},{data:a},{data:o}]=await Promise.all([supabase.from('partners').select('*').eq('id',role.business_id).maybeSingle(),supabase.from('request_assignments').select('request_id,partner_id,is_primary,assigned_at').eq('partner_id',role.business_id).order('assigned_at',{ascending:false}),supabase.from('orders').select('*').eq('partner_id',role.business_id).order('created_at',{ascending:false})]);setPartner(p);const reqIds=(a||[]).map((x:any)=>x.request_id);if(reqIds.length){const {data:r}=await supabase.from('repair_requests').select('id,brand,model,problem_description,preferred_date,preferred_time,postal_code,city,status,created_at,customers(first_name,last_name,phone,email)').in('id',reqIds).order('created_at',{ascending:false});setRequests(r||[])}else setRequests([]);setOrders(o||[])};useEffect(()=>{void load()},[]);
 const complete=async(r:any)=>{const raw=window.prompt('Endgültigen Rechnungsbetrag in € eingeben:');if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<0){onToast('Ungültiger Betrag.');return}const {error}=await supabase!.rpc('partner_complete_order',{p_request_id:r.id,p_value:value});if(error)onToast(error.message);else{onToast('Auftrag abgeschlossen. Abrechnung wurde angelegt.');await load()}};
 return <main className="admin-page"><div className="admin-shell"><aside className="admin-side"><div className="admin-brand">WASCH<span>MATIK</span><small>Partner</small></div><button className="side-btn active"><HomeIcon size={18}/>Dashboard</button><button className="side-btn"><Building2 size={18}/>Betriebsdaten</button><button className="side-btn"><FileText size={18}/>Eigene Anfragen</button><button className="side-btn"><Wallet size={18}/>Eigene Abrechnungen</button><button className="side-btn" onClick={()=>window.location.href='https://waschmatik.de/'}>Website</button><button className="side-btn danger" onClick={()=>void supabase?.auth.signOut()}>Abmelden</button></aside><section className="admin-content"><AdminHeader title={partner?.business_name||'Partnerdashboard'}/><div className="stats-grid"><div className="stat-card"><span>Eigene Anfragen</span><strong>{requests.length}</strong></div><div className="stat-card"><span>Abgeschlossen</span><strong>{requests.filter(x=>x.status==='completed').length}</strong></div><div className="stat-card"><span>Abrechnungen</span><strong>{orders.filter(x=>x.invoice_number).length}</strong></div><div className="stat-card"><span>Offene Provision</span><strong>{money(orders.filter(x=>x.invoice_status!=='bezahlt'&&x.invoice_status!=='storniert').reduce((s:any,x:any)=>s+Number(x.commission_amount||0),0))}</strong></div></div><div className="card"><h3>Eigene Anfragen</h3>{requests.map(r=><div className="mini-row" key={r.id}><b>{r.id.slice(0,8).toUpperCase()}</b><span>{r.problem_description}</span><span className="badge">{r.status}</span>{r.status!=='completed'&&r.status!=='cancelled'&&<button className="small primary" onClick={()=>complete(r)}>Reparatur abgeschlossen</button>}</div>)}{!requests.length&&<div className="empty small">Noch keine Anfragen vorhanden.</div>}</div><div className="card" style={{marginTop:16}}><h3>Eigene Abrechnungen</h3>{orders.filter(x=>x.invoice_number).map(x=><div className="mini-row" key={x.id}><b>{x.invoice_number}</b><span>{money(x.commission_amount)}</span><span className="badge">{x.invoice_status||'offen'}</span></div>)}{!orders.some(x=>x.invoice_number)&&<div className="empty small">Noch keine Abrechnungen vorhanden.</div>}</div></section></div></main>;
}
